### ISSUE TITLE
UnboundLocalError with Python 2.6

### ISSUE THREAD

**Issue by virii** [mixminion/mixminion#3]
Jan 08 21:27:54.140 +0100 [ERROR] Exception delivering message
Jan 08 21:27:54.140 +0100 [ERROR] Traceback (most recent call last):
    File "/usr/local/lib/python2.6/dist-packages/mixminion/server/Modules.py", line 211, in _deliverMessages
    result = self.module.processMessage(packet)
    File "/usr/local/lib/python2.6/dist-packages/mixminion/server/Modules.py", line 1312, in processMessage
    return sendSMTPMessage(self.cfgSection, [address], self.returnAddress, msg)
    File "/usr/local/lib/python2.6/dist-packages/mixminion/server/Modules.py", line 1484, in sendSMTPMessage
    return res
  UnboundLocalError: local variable 'res' referenced before assignment

**Comment by virii** [comment]
Same error when using Python 2.7
